WITH RAW_RATINGS AS (
    SELECT * FROM MOVIELENS.RAW.RAW_RATINGS
)

SELECT 
    USERID AS USER_ID,
    MOVIEID AS MOVIE_ID,
    RATING,
    TO_TIMESTAMP_LTZ(TIMESTAMP) AS RATING_TIMESTAMP
FROM RAW_RATINGS
